CREATE TABLE countries_data (
    country TEXT,
    region TEXT,
    population INTEGER,
    area REAL,
    pop_density REAL,
    coastline REAL,
    net_migration REAL,
    infant_mortality REAL,
    gdp REAL,
    literacy REAL,
    phones REAL,
    arable REAL,
    crops REAL,
    other REAL,
    climate REAL,
    birthrate REAL,
    deathrate REAL,
    agriculture REAL,
    industry REAL,
    service REAL
);
